---
kind: pipeline
name: default

steps:
  - name: Go test
    image: golang:1.13
    environment:
      GO111MODULE: on
    commands:
      - go mod download
      - go test ./... --cover --count=100

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.4.5
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: openware/rango
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild
    when:
      branch:
        - master
        - "*-stable"

  - name: Build container
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/rango
      registry: quay.io
    when:
      branch:
        - master
        - "*-stable"

  - name: "Notify"
    image: quay.io/openware/sdk-citools:2.4.5
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      SDK_BRANCH: ${DRONE_BRANCH}
      SLACK_CHANNEL: peatio
      SLACK_TOKEN:
        from_secret: slack_token
      GITHUB_API_KEY:
        from_secret: kite_bot_key
      TELEGRAM_BOT_TOKEN:
        from_secret: telegram_bot_token
      TELEGRAM_CHAT_ID:
        from_secret: telegram_chat_id
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:postbuild[/drone/src]
    when:
      branch:
        - master
        - "*-stable"

  - name: Prepare debug container version
    image: debian
    commands:
      - echo $(<.tags)-debug > .tags
    when:
        branch:
        - master
        - "*-stable"

  - name: Build debug container
    image: plugins/docker
    settings:
      username:
        from_secret: quay_username
      password:
        from_secret: quay_password
      repo: quay.io/openware/rango
      registry: quay.io
      build_args:
        - BUILD_ARGS=-race
    when:
        branch:
        - master
        - "*-stable"

trigger:
  event:
    - push

image_pull_secrets:
  - dockerconfigjson
